"""make qmj grade and quarter nullable

Revision ID: 01974922fc38
Revises: a706f28b5bbe
Create Date: 2025-12-29 13:01:30.739195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01974922fc38'
down_revision: Union[str, Sequence[str], None] = 'a706f28b5bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qmj', 'grade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('qmj', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qmj', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('qmj', 'grade',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
