"""add_admin_fields_to_user

Revision ID: 52e9946ea0cc
Revises: 113b439ea145
Create Date: 2026-01-10 23:38:32.744872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e9946ea0cc'
down_revision: Union[str, Sequence[str], None] = '113b439ea145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable with server_default first
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    
    # Update existing rows to have False values
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    op.execute("UPDATE users SET is_superuser = false WHERE is_superuser IS NULL")
    
    # Now make columns NOT NULL
    op.alter_column('users', 'is_admin', nullable=False)
    op.alter_column('users', 'is_superuser', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
