"""add_qmj_tables

Revision ID: 764daa5c8f5a
Revises: 9a5bba72f09e
Create Date: 2025-12-29 12:29:54.414609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764daa5c8f5a'
down_revision: Union[str, Sequence[str], None] = '9a5bba72f09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
